name: Multiple Inputs and Condition
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Enter your name'
        required: true
      age: 
        description: 'Enter age'
        required: true
      country:
        description: 'Enter country'
        required: true

jobs:
  check_country:
    runs-on: unbuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Install depenedencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run python script
        run: python main.py "${{github.event.inputs.name  }}" "${{github.event.inputs.age  }}" "${{github.event.inputs.country }}"
      - name: Say Namastey (Only if from india)
        if: ${{github.event.inputs.country == 'India' }}
        run: echo "namaste, ${{github.event.inputs.name }}!"
      
      - name: Test file
        run: pytest

